/**
 * examCalendar.js — Static exam calendar for 2026
 * GET /api/exam-calendar
 */

import { Router } from 'express';

const router = Router();

// ─── Exam Calendar Data (2026) ──────────────────────────────────────────────

const EXAM_CALENDAR = [
  {
    id: 'wbcs',
    name: 'West Bengal Civil Service (WBCS)',
    shortName: 'WBCS',
    conductedBy: 'WBPSC',
    category: 'state-govt',
    officialWebsite: 'https://wbpsc.gov.in',
    frequency: 'Yearly',
    vacancies: '~800',
    events: [
      { label: 'Notification', date: 'Dec 2025', sortDate: '2025-12-01', status: 'completed' },
      { label: 'Application Deadline', date: 'Jan 2026', sortDate: '2026-01-15', status: 'completed' },
      { label: 'Prelims Exam', date: '9 Mar 2026', sortDate: '2026-03-09', status: 'completed' },
      { label: 'Prelims Result', date: 'May 2026 (Expected)', sortDate: '2026-05-15', status: 'upcoming' },
      { label: 'Mains Exam', date: 'Aug 2026 (Expected)', sortDate: '2026-08-01', status: 'tentative' },
      { label: 'Interview', date: 'Nov 2026 (Expected)', sortDate: '2026-11-01', status: 'tentative' },
    ],
  },
  {
    id: 'wb-police-si',
    name: 'West Bengal Police Sub-Inspector (SI)',
    shortName: 'WB Police SI',
    conductedBy: 'WB Police Recruitment Board',
    category: 'state-govt',
    officialWebsite: 'https://wbpolice.gov.in',
    frequency: 'Irregular',
    vacancies: '~1,000',
    events: [
      { label: 'Notification', date: 'Feb 2026', sortDate: '2026-02-01', status: 'completed' },
      { label: 'Application Deadline', date: 'Mar 2026', sortDate: '2026-03-15', status: 'completed' },
      { label: 'Prelims Exam', date: 'Jun 2026 (Expected)', sortDate: '2026-06-15', status: 'tentative' },
      { label: 'Mains Exam', date: 'Sep 2026 (Expected)', sortDate: '2026-09-01', status: 'tentative' },
      { label: 'Physical Test', date: 'Nov 2026 (Expected)', sortDate: '2026-11-01', status: 'tentative' },
    ],
  },
  {
    id: 'wb-police-constable',
    name: 'West Bengal Police Constable',
    shortName: 'WB Police Constable',
    conductedBy: 'WB Police Recruitment Board',
    category: 'state-govt',
    officialWebsite: 'https://wbpolice.gov.in',
    frequency: 'Irregular',
    vacancies: '~8,000',
    events: [
      { label: 'Notification', date: 'Jan 2026', sortDate: '2026-01-10', status: 'completed' },
      { label: 'Application Deadline', date: 'Feb 2026', sortDate: '2026-02-10', status: 'completed' },
      { label: 'Prelims Exam', date: '5 Apr 2026', sortDate: '2026-04-05', status: 'upcoming' },
      { label: 'PMT/PET', date: 'Jul 2026 (Expected)', sortDate: '2026-07-01', status: 'tentative' },
      { label: 'Mains Exam', date: 'Sep 2026 (Expected)', sortDate: '2026-09-15', status: 'tentative' },
    ],
  },
  {
    id: 'wbpsc-clerkship',
    name: 'WBPSC Clerkship Examination',
    shortName: 'WBPSC Clerkship',
    conductedBy: 'WBPSC',
    category: 'state-govt',
    officialWebsite: 'https://wbpsc.gov.in',
    frequency: 'Yearly',
    vacancies: '~2,000',
    events: [
      { label: 'Notification', date: 'Mar 2026 (Expected)', sortDate: '2026-03-01', status: 'tentative' },
      { label: 'Application Deadline', date: 'Apr 2026 (Expected)', sortDate: '2026-04-15', status: 'tentative' },
      { label: 'Exam Date', date: 'Jul 2026 (Expected)', sortDate: '2026-07-15', status: 'tentative' },
      { label: 'Result', date: 'Oct 2026 (Expected)', sortDate: '2026-10-01', status: 'tentative' },
    ],
  },
  {
    id: 'ssc-cgl',
    name: 'SSC CGL (Combined Graduate Level)',
    shortName: 'SSC CGL',
    conductedBy: 'SSC',
    category: 'central-govt',
    officialWebsite: 'https://ssc.gov.in',
    frequency: 'Yearly',
    vacancies: '~17,000+',
    events: [
      { label: 'Notification', date: 'Sep 2025', sortDate: '2025-09-15', status: 'completed' },
      { label: 'Application Deadline', date: 'Oct 2025', sortDate: '2025-10-20', status: 'completed' },
      { label: 'Tier I Exam', date: 'Mar 2026', sortDate: '2026-03-10', status: 'completed' },
      { label: 'Tier I Result', date: 'May 2026 (Expected)', sortDate: '2026-05-10', status: 'upcoming' },
      { label: 'Tier II Exam', date: 'Jun 2026 (Expected)', sortDate: '2026-06-20', status: 'tentative' },
      { label: 'Final Result', date: 'Oct 2026 (Expected)', sortDate: '2026-10-15', status: 'tentative' },
    ],
  },
  {
    id: 'ssc-chsl',
    name: 'SSC CHSL (Combined Higher Secondary Level)',
    shortName: 'SSC CHSL',
    conductedBy: 'SSC',
    category: 'central-govt',
    officialWebsite: 'https://ssc.gov.in',
    frequency: 'Yearly',
    vacancies: '~5,000+',
    events: [
      { label: 'Notification', date: 'Nov 2025', sortDate: '2025-11-15', status: 'completed' },
      { label: 'Application Deadline', date: 'Dec 2025', sortDate: '2025-12-20', status: 'completed' },
      { label: 'Tier I Exam', date: 'Apr 2026 (Expected)', sortDate: '2026-04-15', status: 'upcoming' },
      { label: 'Tier II Exam', date: 'Aug 2026 (Expected)', sortDate: '2026-08-10', status: 'tentative' },
    ],
  },
  {
    id: 'ssc-mts',
    name: 'SSC MTS (Multi-Tasking Staff)',
    shortName: 'SSC MTS',
    conductedBy: 'SSC',
    category: 'central-govt',
    officialWebsite: 'https://ssc.gov.in',
    frequency: 'Yearly',
    vacancies: '~10,000+',
    events: [
      { label: 'Notification', date: 'Jan 2026', sortDate: '2026-01-20', status: 'completed' },
      { label: 'Application Deadline', date: 'Feb 2026', sortDate: '2026-02-28', status: 'completed' },
      { label: 'CBT Exam', date: 'May 2026 (Expected)', sortDate: '2026-05-20', status: 'tentative' },
      { label: 'Result', date: 'Aug 2026 (Expected)', sortDate: '2026-08-15', status: 'tentative' },
    ],
  },
  {
    id: 'ibps-po',
    name: 'IBPS PO (Probationary Officer)',
    shortName: 'IBPS PO',
    conductedBy: 'IBPS',
    category: 'banking',
    officialWebsite: 'https://www.ibps.in',
    frequency: 'Yearly',
    vacancies: '~4,000+',
    events: [
      { label: 'Notification', date: 'Aug 2026 (Expected)', sortDate: '2026-08-01', status: 'tentative' },
      { label: 'Application Deadline', date: 'Sep 2026 (Expected)', sortDate: '2026-09-01', status: 'tentative' },
      { label: 'Prelims Exam', date: 'Oct 2026 (Expected)', sortDate: '2026-10-15', status: 'tentative' },
      { label: 'Mains Exam', date: 'Nov 2026 (Expected)', sortDate: '2026-11-20', status: 'tentative' },
      { label: 'Interview', date: 'Jan 2027 (Expected)', sortDate: '2027-01-15', status: 'tentative' },
    ],
  },
  {
    id: 'ibps-clerk',
    name: 'IBPS Clerk (Clerical Cadre)',
    shortName: 'IBPS Clerk',
    conductedBy: 'IBPS',
    category: 'banking',
    officialWebsite: 'https://www.ibps.in',
    frequency: 'Yearly',
    vacancies: '~6,000+',
    events: [
      { label: 'Notification', date: 'Jul 2026 (Expected)', sortDate: '2026-07-10', status: 'tentative' },
      { label: 'Application Deadline', date: 'Aug 2026 (Expected)', sortDate: '2026-08-10', status: 'tentative' },
      { label: 'Prelims Exam', date: 'Sep 2026 (Expected)', sortDate: '2026-09-20', status: 'tentative' },
      { label: 'Mains Exam', date: 'Oct 2026 (Expected)', sortDate: '2026-10-25', status: 'tentative' },
    ],
  },
  {
    id: 'sbi-po',
    name: 'SBI PO (Probationary Officer)',
    shortName: 'SBI PO',
    conductedBy: 'SBI',
    category: 'banking',
    officialWebsite: 'https://www.sbi.co.in/careers',
    frequency: 'Yearly',
    vacancies: '~2,000+',
    events: [
      { label: 'Notification', date: 'Jan 2026', sortDate: '2026-01-15', status: 'completed' },
      { label: 'Application Deadline', date: 'Feb 2026', sortDate: '2026-02-10', status: 'completed' },
      { label: 'Prelims Exam', date: 'Mar 2026', sortDate: '2026-03-20', status: 'completed' },
      { label: 'Mains Exam', date: 'May 2026 (Expected)', sortDate: '2026-05-10', status: 'upcoming' },
      { label: 'Interview', date: 'Jul 2026 (Expected)', sortDate: '2026-07-15', status: 'tentative' },
    ],
  },
  {
    id: 'upsc-cse',
    name: 'UPSC Civil Services Examination (CSE)',
    shortName: 'UPSC CSE',
    conductedBy: 'UPSC',
    category: 'central-govt',
    officialWebsite: 'https://www.upsc.gov.in',
    frequency: 'Yearly',
    vacancies: '~1,000',
    events: [
      { label: 'Notification', date: 'Feb 2026', sortDate: '2026-02-05', status: 'completed' },
      { label: 'Application Deadline', date: 'Mar 2026', sortDate: '2026-03-03', status: 'completed' },
      { label: 'Prelims Exam', date: '24 May 2026', sortDate: '2026-05-24', status: 'upcoming' },
      { label: 'Mains Exam', date: 'Sep 2026 (Expected)', sortDate: '2026-09-15', status: 'tentative' },
      { label: 'Interview', date: 'Feb 2027 (Expected)', sortDate: '2027-02-01', status: 'tentative' },
    ],
  },
  {
    id: 'nda',
    name: 'NDA (National Defence Academy) Examination',
    shortName: 'NDA',
    conductedBy: 'UPSC',
    category: 'defence',
    officialWebsite: 'https://www.upsc.gov.in',
    frequency: 'Twice a year',
    vacancies: '~400 per cycle',
    events: [
      { label: 'NDA I Notification', date: 'Dec 2025', sortDate: '2025-12-15', status: 'completed' },
      { label: 'NDA I Exam', date: '12 Apr 2026', sortDate: '2026-04-12', status: 'upcoming' },
      { label: 'NDA I SSB Interview', date: 'Jul 2026 (Expected)', sortDate: '2026-07-01', status: 'tentative' },
      { label: 'NDA II Notification', date: 'Jun 2026 (Expected)', sortDate: '2026-06-10', status: 'tentative' },
      { label: 'NDA II Exam', date: 'Sep 2026 (Expected)', sortDate: '2026-09-14', status: 'tentative' },
    ],
  },
  {
    id: 'rrb-ntpc',
    name: 'RRB NTPC (Non-Technical Popular Categories)',
    shortName: 'RRB NTPC',
    conductedBy: 'Railway Recruitment Board',
    category: 'railway',
    officialWebsite: 'https://www.rrbcdg.gov.in',
    frequency: 'Irregular',
    vacancies: '~11,000+',
    events: [
      { label: 'Notification', date: 'Nov 2025', sortDate: '2025-11-20', status: 'completed' },
      { label: 'Application Deadline', date: 'Jan 2026', sortDate: '2026-01-05', status: 'completed' },
      { label: 'CBT Stage 1', date: 'May 2026 (Expected)', sortDate: '2026-05-01', status: 'tentative' },
      { label: 'CBT Stage 2', date: 'Aug 2026 (Expected)', sortDate: '2026-08-01', status: 'tentative' },
      { label: 'Typing/Skill Test', date: 'Nov 2026 (Expected)', sortDate: '2026-11-01', status: 'tentative' },
    ],
  },
  {
    id: 'railway-group-d',
    name: 'Railway Group D (Level 1 Posts)',
    shortName: 'Railway Group D',
    conductedBy: 'Railway Recruitment Board',
    category: 'railway',
    officialWebsite: 'https://www.rrbcdg.gov.in',
    frequency: 'Irregular',
    vacancies: '~32,000+',
    events: [
      { label: 'Notification', date: 'Jan 2026', sortDate: '2026-01-15', status: 'completed' },
      { label: 'Application Deadline', date: 'Feb 2026', sortDate: '2026-02-20', status: 'completed' },
      { label: 'CBT Exam', date: 'Jun 2026 (Expected)', sortDate: '2026-06-01', status: 'tentative' },
      { label: 'PET', date: 'Sep 2026 (Expected)', sortDate: '2026-09-01', status: 'tentative' },
      { label: 'Result', date: 'Dec 2026 (Expected)', sortDate: '2026-12-01', status: 'tentative' },
    ],
  },
  {
    id: 'ctet',
    name: 'CTET (Central Teacher Eligibility Test)',
    shortName: 'CTET',
    conductedBy: 'CBSE',
    category: 'teaching',
    officialWebsite: 'https://ctet.nic.in',
    frequency: 'Twice a year',
    vacancies: 'Eligibility test (no fixed vacancies)',
    events: [
      { label: 'CTET Jul Notification', date: 'Mar 2026', sortDate: '2026-03-10', status: 'completed' },
      { label: 'Application Deadline', date: 'Apr 2026', sortDate: '2026-04-10', status: 'upcoming' },
      { label: 'CTET Jul Exam', date: 'Jul 2026 (Expected)', sortDate: '2026-07-06', status: 'tentative' },
      { label: 'CTET Dec Notification', date: 'Sep 2026 (Expected)', sortDate: '2026-09-15', status: 'tentative' },
      { label: 'CTET Dec Exam', date: 'Dec 2026 (Expected)', sortDate: '2026-12-20', status: 'tentative' },
    ],
  },
  {
    id: 'wb-tet',
    name: 'WB TET (West Bengal Teacher Eligibility Test)',
    shortName: 'WB TET',
    conductedBy: 'WB Board of Primary Education',
    category: 'teaching',
    officialWebsite: 'https://wbbpe.org',
    frequency: 'Yearly',
    vacancies: 'Eligibility test (no fixed vacancies)',
    events: [
      { label: 'Notification', date: 'Apr 2026 (Expected)', sortDate: '2026-04-01', status: 'tentative' },
      { label: 'Application Deadline', date: 'May 2026 (Expected)', sortDate: '2026-05-10', status: 'tentative' },
      { label: 'Exam Date', date: 'Jul 2026 (Expected)', sortDate: '2026-07-20', status: 'tentative' },
      { label: 'Result', date: 'Sep 2026 (Expected)', sortDate: '2026-09-10', status: 'tentative' },
    ],
  },
  {
    id: 'jtet',
    name: 'JTET (Jharkhand Teacher Eligibility Test)',
    shortName: 'JTET',
    conductedBy: 'JAC (Jharkhand Academic Council)',
    category: 'teaching',
    officialWebsite: 'https://jac.jharkhand.gov.in',
    frequency: 'Irregular',
    vacancies: 'Eligibility test (no fixed vacancies)',
    events: [
      { label: 'Notification', date: 'May 2026 (Expected)', sortDate: '2026-05-01', status: 'tentative' },
      { label: 'Application Deadline', date: 'Jun 2026 (Expected)', sortDate: '2026-06-10', status: 'tentative' },
      { label: 'Exam Date', date: 'Aug 2026 (Expected)', sortDate: '2026-08-20', status: 'tentative' },
      { label: 'Result', date: 'Oct 2026 (Expected)', sortDate: '2026-10-15', status: 'tentative' },
    ],
  },
];

// ─── GET /api/exam-calendar ─────────────────────────────────────────────────

router.get('/exam-calendar', (_req, res) => {
  res.json({
    success: true,
    count: EXAM_CALENDAR.length,
    exams: EXAM_CALENDAR,
  });
});

export default router;
